### ISSUE TITLE
VPN mode or TUN doesnt work 

### ISSUE THREAD

**Issue by MaxMaster1984** [AntiNeko/NekoXray#12]
## 建议的必要性
Hi

Windows 11 64x
latest version of your program
vmess protocol
sing-bix core

when enable TUN MODE i get error

FO[0011] [3142719794 0ms] inbound/tun[tun-in]: inbound packet connection to 8.8.8.8:53
INFO[0011] [2538348858 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:49669
INFO[0011] [2538348858 0ms] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
ERROR[0011] dns: exchange failed for www.msftncsi.com. IN A: Post "https://dns.google/dns-query": context deadline exceeded
ERROR[0011] dns: exchange failed for www.msftncsi.com. IN A: Post "https://dns.google/dns-query": context deadline exceeded
ERROR[0011] dns: exchange failed for geo.prod.do.dsp.mp.microsoft.com. IN A: Post "https://dns.google/dns-query": context deadline exceeded
ERROR[0011] dns: exchange failed for geo.prod.do.dsp.mp.microsoft.com. IN A: Post "https://dns.google/dns-query": context deadline exceeded
ERROR[0011] dns: exchange failed for geo.prod.do.dsp.mp.microsoft.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0011] dns: exchange failed for geo.prod.do.dsp.mp.microsoft.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0011] dns: exchange failed for geo.prod.do.dsp.mp.microsoft.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0011] dns: exchange failed for geo.prod.do.dsp.mp.microsoft.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0012] dns: exchange failed for mtalk.google.com. IN A: Post "https://dns.google/dns-query": context deadline exceeded
ERROR[0012] dns: exchange failed for mtalk.google.com. IN A: Post "https://dns.google/dns-query": context deadline exceeded
ERROR[0012] dns: exchange failed for mtalk.google.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0012] dns: exchange failed for mtalk.google.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0012] dns: exchange failed for mtalk.google.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0012] dns: exchange failed for mtalk.google.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0012] dns: exchange failed for www.msftncsi.com. IN A: Post "https://dns.google/dns-query": context deadline exceeded
ERROR[0012] dns: exchange failed for www.msftncsi.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0012] dns: exchange failed for www.msftncsi.com. IN A: Post "https://dns.google/dns-query": context canceled
ERROR[0012] dns: exchange failed for www.msftncsi.com. IN A: Post "https://dns.google/dns-query": context canceled
INFO[0012] [3752814993 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:50260
INFO[0012] [3752814993 0ms] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0013] [3003817842 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:55719
INFO[0013] [3003817842 0ms] inbound/tun[tun-in]: inbound packet connection to 172.19.0.2:53
INFO[0013] [1644143011 0ms] inbound/tun[tun-in]: inbound connection from 172.19.0.1:4205
INFO[0013] [1644143011 0ms] inbound/tun[tun-in]: inbound connection to 52.184.213.21:443
INFO[0013] [1644143011 1ms] outbound/vmess[proxy]: outbound connection to 52.184.213.21:443
ERROR[0013] [1644143011 1ms] inbound/tun[tun-in]: dial tcp 5.61.42.232:13085: connectex: The requested address is not valid in its context.
INFO[0014] [123938587 0ms] inbound/tun[tun-in]: inbound connection from 172.19.0.1:4211
INFO[0014] [123938587 0ms] inbound/tun[tun-in]: inbound connection to 64.233.165.188:443
INFO[0014] [123938587 1ms] outbound/vmess[proxy]: outbound connection to 64.233.165.188:443
ERROR[0014] [123938587 2ms] inbound/tun[tun-in]: dial tcp 5.61.42.232:13085: connectex: The requested address is not valid in its context.
INFO[0014] [770152746 0ms] inbound/tun[tun-in]: inbound packet connection from 172.19.0.1:57531
INFO[0014] [770152746 0ms] inbound/tun[tun-in]: inbound packet connection to 192.168.1.89:161
INFO[0014] [770152746 0ms] outbound/vmess[proxy]: outbound packet connection to 192.168.1.89:161
ERROR[0014] [770152746 0ms] inbound/tun[tun-in]: dial tcp 5.61.42.232:13085: connectex: The requested address is not valid in its context.
ERROR[0015] dns: exchange failed for mtalk.google.com. IN A: Post "https://dns.google/dns-query": context deadline exceeded

**Comment by MaxMaster1984** [comment]
proxy mode works fine, but i wanna send all traffic to vpn

**Comment by xchacha20-poly1305** [comment]
Try:

* Change your underlying DNS (Basic Settings -> Core -> Core Options) to others.(like 8.8.8.8)

* Do not use DNS over HTTPS as your remote DNS.
