### ISSUE TITLE
BUG: Rename the release archives to "nekoxray"

### ISSUE THREAD

**Issue by SudoerReodus** [AntiNeko/NekoXray#16]
Currently the release archives are named "nekoray" which is the same as the upstream release.
This makes it confusing as to which version the archive files belong to (nekoray or nekoxray) after you save them in your filesystem.

It also means that you can't put the archive files in the same folder or extract them in the same parent folder without manually renaming the archive files first.

Please rename the release archives to "nekoxray" to make it easier to distinguish between version. 
(Just like how CatBox release apks are named "CB4A" as opposed to NekoBox release apks which are named "NB4A")

Thanks

**Comment by xchacha20-poly1305** [comment]
Nope
